[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = [
    "src/models/**"
  ]

[dev]
  command = "npm run start"
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback redirect — *this is what fixes refreshes*
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
