[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = [
    "src/models/**"
  ]

[dev]
  command = "npm run start"
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[context.production]
  [[context.production.redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
